controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
  path: /login
  methods: ['POST']

app_reset_password:
    path: /reset-password/reset/{token}
    controller: App\Controller\ResetPasswordController::reset