lexik_jwt_authentication:
    secret_key: '%env(base64:JWT_SECRET_KEY)%'
    public_key: '%env(base64:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    api_platform:
        check_path: /api/login_check
        username_path: ut_mail
        password_path: security.credentials.password
    blocklist_token:
        enabled: true
        cache: cache.app